name: Build LaTeX document
on:
  push:
    branches: trunk
  pull_request:
    branches: trunk

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install -y texlive-xetex texlive-latex-base fonts-freefont-otf
          sudo fc-cache -f
      - name: Compile LaTeX document
        run: |
          cd Edition02/latex
          xelatex -synctex=1 -interaction=nonstopmode "main".tex
